site_name: Salvando Vidas atraves do Esporte
repo_url: https://github.com/mdsreq-fga-unb/REQ-2026.1-T02-Salvando-Vidas-atraves-do-Esporte
site_description: Documentação do projeto Salvando Vidas atraves do Esporte
repo_name: REQ-2026.1-T02-Salvando-Vidas-atraves-do-Esporte

theme:
  name: material
  palette:
    scheme: slate

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - Visão do Produto e Projeto:
      - 1. Cenário Atual do Cliente e do Negócio: Visão do Produto e Projeto/cenarioAtualDoClienteEDoNegocio.md
      - 2. Proposta da Solução: Visão do Produto e Projeto/PropostaDaSolucao.md
      - 3. Interveção Social: Visão do Produto e Projeto/intervencaoSocial.md
      - 4. Estratégias de Engenharia de Software: Visão do Produto e Projeto/estrategiasDeEngenhariaDeSoftware.md
      - 5. Engenharia de Requisitos: Visão do Produto e Projeto/engenhariaDeRequisitos.md
      - 6. Cronograma e Entregas: Visão do Produto e Projeto/cronogramaEEntregas.md
      - 7. Interação entre Equipe e Cliente: Visão do Produto e Projeto/interacaoEntreEquipeECliente.md
      - 9. DoR e DoD: Visão do Produto e Projeto/DoREDoD.md
      - 11. Liçoes Aprendidas: Visão do Produto e Projeto/licoesAprendidas.md
  - Entregas:
    - "Entregas": Entregas/entregas.md
  - Atas:
    - "Atas": Atas/atas.md
  - Referências: assets/referencias.md
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
