site_name: Documentação Grupo Na minha Maquina Funciona
site_description: Documentação do projeto Salvando Vidas atraves do Esporte

theme:
  name: material

nav:
  - Home: index.md

  - Visão do Produto e Projeto:
      - 1. Cenário Atual do Cliente e do Negócio: Visão do Produto e Projeto/index.md