// Mocks generated by Mockito 5.4.6 from annotations
// in salvando_vidas/test/mocks/local_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mobx/mobx.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:salvando_vidas/data/services/user_service.dart' as _i4;
import 'package:salvando_vidas/data/stores/login/login_form.dart' as _i2;
import 'package:salvando_vidas/data/supabase_call.dart' as _i7;
import 'package:salvando_vidas/domain/local_user/local_user.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginFormErrorState_0 extends _i1.SmartFake
    implements _i2.LoginFormErrorState {
  _FakeLoginFormErrorState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReactiveContext_1 extends _i1.SmartFake
    implements _i3.ReactiveContext {
  _FakeReactiveContext_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i4.UserService {
  @override
  bool get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set localUser(_i5.LocalUser? value) => super.noSuchMethod(
    Invocation.setter(#localUser, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.Result<bool>> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<bool>>);

  @override
  _i6.Future<_i7.Result<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<bool>> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i6.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#isLoggedIn, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#isLoggedIn, []),
              ),
            ),
          )
          as _i6.Future<_i7.Result<bool>>);

  @override
  _i6.Future<_i7.Result<_i5.LocalUser?>> getLocalUser(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalUser, [user]),
            returnValue: _i6.Future<_i7.Result<_i5.LocalUser?>>.value(
              _i8.dummyValue<_i7.Result<_i5.LocalUser?>>(
                this,
                Invocation.method(#getLocalUser, [user]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<_i5.LocalUser?>>.value(
                  _i8.dummyValue<_i7.Result<_i5.LocalUser?>>(
                    this,
                    Invocation.method(#getLocalUser, [user]),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<_i5.LocalUser?>>);

  @override
  _i6.Future<_i7.Result<List<_i5.LocalUser>>> listUsers() =>
      (super.noSuchMethod(
            Invocation.method(#listUsers, []),
            returnValue: _i6.Future<_i7.Result<List<_i5.LocalUser>>>.value(
              _i8.dummyValue<_i7.Result<List<_i5.LocalUser>>>(
                this,
                Invocation.method(#listUsers, []),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i7.Result<List<_i5.LocalUser>>>.value(
                  _i8.dummyValue<_i7.Result<List<_i5.LocalUser>>>(
                    this,
                    Invocation.method(#listUsers, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<List<_i5.LocalUser>>>);

  @override
  _i6.Future<_i7.Result<void>> registerUser(
    String? email,
    String? password,
    String? nome,
    String? telefone,
    String? cpf,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [
              email,
              password,
              nome,
              telefone,
              cpf,
            ]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#registerUser, [
                  email,
                  password,
                  nome,
                  telefone,
                  cpf,
                ]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#registerUser, [
                  email,
                  password,
                  nome,
                  telefone,
                  cpf,
                ]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<void>> deleteUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deleteUser, [id]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deleteUser, [id]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<_i7.Result<void>> updateUser({
    required String? id,
    String? email,
    String? password,
    String? nome,
    String? telefone,
    String? cpf,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {
              #id: id,
              #email: email,
              #password: password,
              #nome: nome,
              #telefone: telefone,
              #cpf: cpf,
            }),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#updateUser, [], {
                  #id: id,
                  #email: email,
                  #password: password,
                  #nome: nome,
                  #telefone: telefone,
                  #cpf: cpf,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#updateUser, [], {
                  #id: id,
                  #email: email,
                  #password: password,
                  #nome: nome,
                  #telefone: telefone,
                  #cpf: cpf,
                }),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);
}

/// A class which mocks [LoginFormStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginFormStore extends _i1.Mock implements _i2.LoginFormStore {
  @override
  _i2.LoginFormErrorState get error =>
      (super.noSuchMethod(
            Invocation.getter(#error),
            returnValue: _FakeLoginFormErrorState_0(
              this,
              Invocation.getter(#error),
            ),
            returnValueForMissingStub: _FakeLoginFormErrorState_0(
              this,
              Invocation.getter(#error),
            ),
          )
          as _i2.LoginFormErrorState);

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get senha =>
      (super.noSuchMethod(
            Invocation.getter(#senha),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#senha),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#senha),
            ),
          )
          as String);

  @override
  bool get canLogin =>
      (super.noSuchMethod(
            Invocation.getter(#canLogin),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set email(String? value) => super.noSuchMethod(
    Invocation.setter(#email, value),
    returnValueForMissingStub: null,
  );

  @override
  set senha(String? value) => super.noSuchMethod(
    Invocation.setter(#senha, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.ReactiveContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeReactiveContext_1(
              this,
              Invocation.getter(#context),
            ),
            returnValueForMissingStub: _FakeReactiveContext_1(
              this,
              Invocation.getter(#context),
            ),
          )
          as _i3.ReactiveContext);

  @override
  void validateEmail(String? value) => super.noSuchMethod(
    Invocation.method(#validateEmail, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void validatePassword(String? value) => super.noSuchMethod(
    Invocation.method(#validatePassword, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setupValidations() => super.noSuchMethod(
    Invocation.method(#setupValidations, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
