// Mocks generated by Mockito 5.4.6 from annotations
// in salvando_vidas/test/ui/aluno_expandable_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:logger/src/log_level.dart' as _i7;
import 'package:logger/src/logger.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:salvando_vidas/data/services/aluno_service/aluno_service.dart'
    as _i4;
import 'package:salvando_vidas/domain/aluno/aluno.dart' as _i2;
import 'package:salvando_vidas/domain/responsavel/responsavel.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAluno_0 extends _i1.SmartFake implements _i2.Aluno {
  _FakeAluno_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponsavel_1 extends _i1.SmartFake implements _i3.Responsavel {
  _FakeResponsavel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AlunoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlunoService extends _i1.Mock implements _i4.AlunoService {
  @override
  _i5.Future<_i2.Aluno> cadastrarAluno(_i2.Aluno? aluno) =>
      (super.noSuchMethod(
            Invocation.method(#cadastrarAluno, [aluno]),
            returnValue: _i5.Future<_i2.Aluno>.value(
              _FakeAluno_0(this, Invocation.method(#cadastrarAluno, [aluno])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Aluno>.value(
              _FakeAluno_0(this, Invocation.method(#cadastrarAluno, [aluno])),
            ),
          )
          as _i5.Future<_i2.Aluno>);

  @override
  _i5.Future<_i3.Responsavel> cadastrarResponsavel(
    _i3.Responsavel? responsavel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cadastrarResponsavel, [responsavel]),
            returnValue: _i5.Future<_i3.Responsavel>.value(
              _FakeResponsavel_1(
                this,
                Invocation.method(#cadastrarResponsavel, [responsavel]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Responsavel>.value(
              _FakeResponsavel_1(
                this,
                Invocation.method(#cadastrarResponsavel, [responsavel]),
              ),
            ),
          )
          as _i5.Future<_i3.Responsavel>);

  @override
  _i5.Future<List<_i2.Aluno>> listarAlunos() =>
      (super.noSuchMethod(
            Invocation.method(#listarAlunos, []),
            returnValue: _i5.Future<List<_i2.Aluno>>.value(<_i2.Aluno>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Aluno>>.value(
              <_i2.Aluno>[],
            ),
          )
          as _i5.Future<List<_i2.Aluno>>);

  @override
  _i5.Future<List<_i2.Aluno>> listarAlunosTurma(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#listarAlunosTurma, [id]),
            returnValue: _i5.Future<List<_i2.Aluno>>.value(<_i2.Aluno>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Aluno>>.value(
              <_i2.Aluno>[],
            ),
          )
          as _i5.Future<List<_i2.Aluno>>);

  @override
  _i5.Future<List<_i3.Responsavel>> listarResponsaveis() =>
      (super.noSuchMethod(
            Invocation.method(#listarResponsaveis, []),
            returnValue: _i5.Future<List<_i3.Responsavel>>.value(
              <_i3.Responsavel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i3.Responsavel>>.value(
              <_i3.Responsavel>[],
            ),
          )
          as _i5.Future<List<_i3.Responsavel>>);

  @override
  _i5.Future<void> atualizaAluno(int? id, Map<String, dynamic>? diff) =>
      (super.noSuchMethod(
            Invocation.method(#atualizaAluno, [id, diff]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> atualizaResponsavel(int? id, Map<String, dynamic>? diff) =>
      (super.noSuchMethod(
            Invocation.method(#atualizaResponsavel, [id, diff]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deletaAluno(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletaAluno, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deletaResponsavel(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletaResponsavel, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i6.Logger {
  @override
  _i5.Future<void> get init =>
      (super.noSuchMethod(
            Invocation.getter(#init),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #v,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #t,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #d,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #i,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #w,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #e,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #wtf,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #f,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    _i7.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [level, message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool isClosed() =>
      (super.noSuchMethod(
            Invocation.method(#isClosed, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
