// Mocks generated by Mockito 5.4.6 from annotations
// in salvando_vidas/test/ui/configuracao_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:salvando_vidas/data/services/user_service/user_service.dart'
    as _i2;
import 'package:salvando_vidas/data/supabase_call.dart' as _i5;
import 'package:salvando_vidas/domain/local_user/local_user.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i2.UserService {
  @override
  bool get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set localUser(_i3.LocalUser? user) => super.noSuchMethod(
    Invocation.setter(#localUser, user),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i3.LocalUser?> getLocalUser(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalUser, [user]),
            returnValue: _i4.Future<_i3.LocalUser?>.value(),
            returnValueForMissingStub: _i4.Future<_i3.LocalUser?>.value(),
          )
          as _i4.Future<_i3.LocalUser?>);

  @override
  _i4.Future<List<_i3.LocalUser>> listUsers() =>
      (super.noSuchMethod(
            Invocation.method(#listUsers, []),
            returnValue: _i4.Future<List<_i3.LocalUser>>.value(
              <_i3.LocalUser>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i3.LocalUser>>.value(
              <_i3.LocalUser>[],
            ),
          )
          as _i4.Future<List<_i3.LocalUser>>);

  @override
  _i4.Future<void> registerUser(_i3.LocalUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUser(Map<String, dynamic>? diff) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [diff]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> inactivateUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#inactivateUser, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reactivateUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#reactivateUser, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
