// Mocks generated by Mockito 5.4.6 from annotations
// in salvando_vidas/test/data/stores/historico_emprestimos_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:salvando_vidas/data/services/aluno_service/aluno_service.dart'
    as _i7;
import 'package:salvando_vidas/data/services/kimono_service/kimono_service.dart'
    as _i5;
import 'package:salvando_vidas/data/services/user_service/user_service.dart'
    as _i8;
import 'package:salvando_vidas/data/supabase_call.dart' as _i10;
import 'package:salvando_vidas/domain/aluno/aluno.dart' as _i3;
import 'package:salvando_vidas/domain/kimono/kimono.dart' as _i2;
import 'package:salvando_vidas/domain/local_user/local_user.dart' as _i9;
import 'package:salvando_vidas/domain/responsavel/responsavel.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDoacao_0 extends _i1.SmartFake implements _i2.Doacao {
  _FakeDoacao_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePerda_1 extends _i1.SmartFake implements _i2.Perda {
  _FakePerda_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmprestimo_2 extends _i1.SmartFake implements _i2.Emprestimo {
  _FakeEmprestimo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAluno_3 extends _i1.SmartFake implements _i3.Aluno {
  _FakeAluno_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponsavel_4 extends _i1.SmartFake implements _i4.Responsavel {
  _FakeResponsavel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KimonoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKimonoService extends _i1.Mock implements _i5.KimonoService {
  MockKimonoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Doacao> cadastrarDoacao(_i2.Doacao? doacao) =>
      (super.noSuchMethod(
            Invocation.method(#cadastrarDoacao, [doacao]),
            returnValue: _i6.Future<_i2.Doacao>.value(
              _FakeDoacao_0(
                this,
                Invocation.method(#cadastrarDoacao, [doacao]),
              ),
            ),
          )
          as _i6.Future<_i2.Doacao>);

  @override
  _i6.Future<_i2.Perda> cadastrarPerda(_i2.Perda? perda) =>
      (super.noSuchMethod(
            Invocation.method(#cadastrarPerda, [perda]),
            returnValue: _i6.Future<_i2.Perda>.value(
              _FakePerda_1(this, Invocation.method(#cadastrarPerda, [perda])),
            ),
          )
          as _i6.Future<_i2.Perda>);

  @override
  _i6.Future<_i2.Emprestimo> cadastrarEmprestimo(_i2.Emprestimo? emprestimo) =>
      (super.noSuchMethod(
            Invocation.method(#cadastrarEmprestimo, [emprestimo]),
            returnValue: _i6.Future<_i2.Emprestimo>.value(
              _FakeEmprestimo_2(
                this,
                Invocation.method(#cadastrarEmprestimo, [emprestimo]),
              ),
            ),
          )
          as _i6.Future<_i2.Emprestimo>);

  @override
  _i6.Future<List<_i2.Doacao>> listarDoacoes() =>
      (super.noSuchMethod(
            Invocation.method(#listarDoacoes, []),
            returnValue: _i6.Future<List<_i2.Doacao>>.value(<_i2.Doacao>[]),
          )
          as _i6.Future<List<_i2.Doacao>>);

  @override
  _i6.Future<List<_i2.Perda>> listarPerdas() =>
      (super.noSuchMethod(
            Invocation.method(#listarPerdas, []),
            returnValue: _i6.Future<List<_i2.Perda>>.value(<_i2.Perda>[]),
          )
          as _i6.Future<List<_i2.Perda>>);

  @override
  _i6.Future<List<_i2.Emprestimo>> listarEmprestimos() =>
      (super.noSuchMethod(
            Invocation.method(#listarEmprestimos, []),
            returnValue: _i6.Future<List<_i2.Emprestimo>>.value(
              <_i2.Emprestimo>[],
            ),
          )
          as _i6.Future<List<_i2.Emprestimo>>);

  @override
  _i6.Future<List<_i2.Estoque>> obterEstoque() =>
      (super.noSuchMethod(
            Invocation.method(#obterEstoque, []),
            returnValue: _i6.Future<List<_i2.Estoque>>.value(<_i2.Estoque>[]),
          )
          as _i6.Future<List<_i2.Estoque>>);

  @override
  _i6.Future<void> retornarEmprestimo(_i2.Emprestimo? emprestimo) =>
      (super.noSuchMethod(
            Invocation.method(#retornarEmprestimo, [emprestimo]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AlunoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlunoService extends _i1.Mock implements _i7.AlunoService {
  MockAlunoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Aluno> cadastrarAluno(_i3.Aluno? aluno) =>
      (super.noSuchMethod(
            Invocation.method(#cadastrarAluno, [aluno]),
            returnValue: _i6.Future<_i3.Aluno>.value(
              _FakeAluno_3(this, Invocation.method(#cadastrarAluno, [aluno])),
            ),
          )
          as _i6.Future<_i3.Aluno>);

  @override
  _i6.Future<_i4.Responsavel> cadastrarResponsavel(
    _i4.Responsavel? responsavel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cadastrarResponsavel, [responsavel]),
            returnValue: _i6.Future<_i4.Responsavel>.value(
              _FakeResponsavel_4(
                this,
                Invocation.method(#cadastrarResponsavel, [responsavel]),
              ),
            ),
          )
          as _i6.Future<_i4.Responsavel>);

  @override
  _i6.Future<List<_i3.Aluno>> listarAlunos() =>
      (super.noSuchMethod(
            Invocation.method(#listarAlunos, []),
            returnValue: _i6.Future<List<_i3.Aluno>>.value(<_i3.Aluno>[]),
          )
          as _i6.Future<List<_i3.Aluno>>);

  @override
  _i6.Future<List<_i3.Aluno>> listarAlunosTurma(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#listarAlunosTurma, [id]),
            returnValue: _i6.Future<List<_i3.Aluno>>.value(<_i3.Aluno>[]),
          )
          as _i6.Future<List<_i3.Aluno>>);

  @override
  _i6.Future<List<_i4.Responsavel>> listarResponsaveis() =>
      (super.noSuchMethod(
            Invocation.method(#listarResponsaveis, []),
            returnValue: _i6.Future<List<_i4.Responsavel>>.value(
              <_i4.Responsavel>[],
            ),
          )
          as _i6.Future<List<_i4.Responsavel>>);

  @override
  _i6.Future<void> atualizaAluno(int? id, Map<String, dynamic>? diff) =>
      (super.noSuchMethod(
            Invocation.method(#atualizaAluno, [id, diff]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> atualizaResponsavel(int? id, Map<String, dynamic>? diff) =>
      (super.noSuchMethod(
            Invocation.method(#atualizaResponsavel, [id, diff]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deletaAluno(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletaAluno, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deletaResponsavel(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletaResponsavel, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i8.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  set localUser(_i9.LocalUser? user) => super.noSuchMethod(
    Invocation.setter(#localUser, user),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i9.LocalUser?> getLocalUser(_i10.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalUser, [user]),
            returnValue: _i6.Future<_i9.LocalUser?>.value(),
          )
          as _i6.Future<_i9.LocalUser?>);

  @override
  _i6.Future<List<_i9.LocalUser>> listUsers() =>
      (super.noSuchMethod(
            Invocation.method(#listUsers, []),
            returnValue: _i6.Future<List<_i9.LocalUser>>.value(
              <_i9.LocalUser>[],
            ),
          )
          as _i6.Future<List<_i9.LocalUser>>);

  @override
  _i6.Future<void> registerUser(_i9.LocalUser? user) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUser(Map<String, dynamic>? diff) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [diff]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> inactivateUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#inactivateUser, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> reactivateUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#reactivateUser, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
