set dotenv-load

version := shell("grep 'version:' pubspec.yaml")
github := env('GITHUB')

default:
    just --list

deploy:
    @echo "Clean existing repository"
    flutter clean

    @echo "Getting packages..."
    flutter pub get

    @echo "Building for web..."
    flutter build web --release

    @echo "Deploying to git repository"
    cd build/web && \
    git init && \
    git add . && \
    git commit -m "Deploy {{ version }}" && \
    git branch -M main && \
    git remote add origin {{ github }} && \
    git push -u -f origin main
