name: Flutter Test on Pull Request

on: pull_request

jobs:
  flutter-test:
    name: Test Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'

      - name: Install dependencies
        run: |
          cd src
          flutter pub get

      - name: Run flutter test
        run: |
          cd src
          flutter test --no-pub --coverage --coverage-path=./coverage/lcov.info

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: code-coverage
          path: src/coverage/lcov.info

  generate-report:
    name: Test Flutter
    needs: flutter-test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8.0.1
        with:
          path: coverage
          pattern: code-coverage*
          merge-multiple: true
      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@v7.0.12
        with:
          coverage-files: coverage/lcov*
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: src
    